env:
  browser: true
  es2021: true
  mocha: true
extends: standard
globals:
  Bun: readable
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  space-before-function-paren: ["error", "never"]
